#page title
page_title                                : Matchpulse

# App Info
ios_app_id                                : 6744074075
ios_app_country                           : de

appstore_link                             : 
playstore_link                            : 
presskit_download_link                    : https://matchpulse.de

app_icon                                  : assets/appicon.png
app_name                                  : Matchpulse
app_price                                 : Kostenlos
app_description                           : Dein Spiel - dein Sport.

enable_smart_app_banner                   : true

# Information About Yourself
your_name                                 : Conor Fiele
your_link                                 : https://matchpulse.de
your_city                                 : Deutschland
email_address                             : support@matchpulse.de
linkedin_username                         : 
linkedin_company                          : 
facebook_username                         : 
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          : 
mastodon_link                             : 

# Feature List
features                                  :

  - title                                 : Live-Scores & Spielstände
    description                           : Verfolge Echtzeit-Ergebnisse und Spielstände aller wichtigen Fußball-Ligen weltweit.
    fontawesome_icon_name                 : trophy
    
  - title                                 : Personalisierte Benachrichtigungen
    description                           : Erhalte Push-Benachrichtigungen für Tore, Karten, Spielbeginn und wichtige Ereignisse deiner Lieblingsmannschaften.
    fontawesome_icon_name                 : bell

  - title                                 : Übersichtliche Spielpläne
    description                           : Plane deine Fußballabende mit detaillierten Spielplänen und Tabellen aller Ligen.
    fontawesome_icon_name                 : calendar

  - title                                 : Favoritenverwaltung
    description                           : Füge deine Lieblingsmannschaften hinzu und verpasse keine wichtigen Spiele mehr.
    fontawesome_icon_name                 : heart

  - title                                 : Detaillierte Statistiken
    description                           : Erhalte umfangreiche Spielstatistiken und Analysen für jedes Spiel.
    fontawesome_icon_name                 : chart-bar
  
  - title                                 : Kostenlos & ohne Werbung
    description                           : Genieße alle Funktionen ohne Einschränkungen und ohne störende Werbung.
    fontawesome_icon_name                 : gift

  - title                                 : Alle wichtigen Ligen
    description                           : Bundesliga, Premier League, La Liga, Serie A, Ligue 1 und viele mehr.
    fontawesome_icon_name                 : globe

  - title                                 : Modernes Design
    description                           : Intuitive Benutzeroberfläche mit klarem, modernem Design.
    fontawesome_icon_name                 : paint-brush

  - title                                 : Echtzeit-Updates
    description                           : Sofortige Aktualisierungen für Spielstände und Ereignisse.
    fontawesome_icon_name                 : bolt

  - title                                 : Offline-Funktionalität
    description                           : Zugriff auf gespeicherte Daten auch ohne Internetverbindung.
    fontawesome_icon_name                 : wifi

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
